#!/bin/bash

dirName=$(dirname $0)
progName=$(basename $0)

success()   { [ -t 1 ] && tput setaf 2; echo -n "[OK] ";    [ -t 1 ] && tput sgr0; echo "$*"; }
error()     { [ -t 1 ] && tput setaf 1; echo -n "[ERROR] "; [ -t 1 ] && tput sgr0; echo "$*"; }
fatal()     { [ -t 1 ] && tput setaf 1; echo -n "[ERROR] "; [ -t 1 ] && tput sgr0; echo "$*"; exit 1; }
highlight() { [ -t 1 ] && tput setaf 3; echo    "$*";       [ -t 1 ] && tput sgr0; return 0; }

set -euo pipefail
trap "fatal 'Non-null value returned by last executed command'" ERR

# zim style
wget --quiet -O $dirName/usermode/functions/assets/zim-style.conf https://gandrille.github.io/linux-notes/Softs/zim/style.conf
success "zim style.conf updated"
