#!/bin/bash

dirName=$(dirname $0)
progName=$(basename $0)

success()   { [ -t 1 ] && tput setaf 2; echo -n "[OK] ";    [ -t 1 ] && tput sgr0; echo "$*"; }
error()     { [ -t 1 ] && tput setaf 1; echo -n "[ERROR] "; [ -t 1 ] && tput sgr0; echo "$*"; }
fatal()     { [ -t 1 ] && tput setaf 1; echo -n "[ERROR] "; [ -t 1 ] && tput sgr0; echo "$*"; exit 1; }
highlight() { [ -t 1 ] && tput setaf 3; echo    "$*";       [ -t 1 ] && tput sgr0; return 0; }

set -euo pipefail
trap "fatal 'Non-null value returned by last executed command'" ERR

cd $dirName

# we need go-bindata
type go-bindata &> /dev/null || fatal "Please install go-bindata first (for instance, using apt under debian)"

# zim style
wget --quiet -O $dirName/assets/resources/zim-style.conf https://gandrille.github.io/linux-notes/Softs/zim/style.conf
success "zim style.conf updated"

# Firefox user config
wget --quiet -O $dirName/assets/resources/firefox-user.js https://gandrille.github.io/linux-notes/Softs/Firefox/Config/user.js
success "Firefox config updated"

# generate
PATH=$PATH:$GOPATH/bin
go generate -x assets/assetsgenerator.go
success "go bindata generated"
